# config.yaml

wta:
multiplex:

threads_number:
sequencing_technology:
genes_to_be_allele_typed: # a list
raw_data_fastq_list: # a list; fastq files must have the following format: {dir_raw_fastq}/*.R{1/2}.fastq.gz

sample_tag_seqs: # only if multiplexed

read_bp_length: # only if amplicon-based
amplicon_cDNA_fasta: # only if amplicon-based

single_end_samples: # only if whole-transcriptome-based
reference_genome_gtf: # only if whole-transcriptome-based
reference_genome_fasta: # only if whole-transcriptome-based
