# environment.yaml

channels:
  - conda-forge
  - bioconda

dependencies:
  # Snakemake for workflow management
  - snakemake >=7.3

  # R and tidyverse for data analysis
  - r-base >=4.3
  - r-tidyverse =2.0.0
  - r-Matrix =1.6-1.1

  # Bioconductor packages for bioinformatics analysis
  - bioconductor-ShortRead =1.58.0
  - bioconductor-sparseMatrixStats =1.12.2

  # Tools for (sc)RNA-seq analysis
  - kb-python =0.27.3
  - kallisto =0.48.0
  - seqkit =2.5.1
  - seqtk =1.4
  - star =2.7.10b
  - samtools =1.15

  # HLA typing tool
  - arcas-hla =0.5.0