# R

## this R script reads the count matrix generated by kallisto, where rows are cell barcodes and columns are sample tag names
## it identifies the dominant sample tag for each cell by checking if the maximum count for a tag is at least 75% of the total counts for that cell
## if this condition is met, the cell is assigned to the sample tag with the highest count
## otherwise, the cell is labeled as 'Multiplet' and removed
## the final output is a table of cellular barcodes and their corresponding sample tags

suppressPackageStartupMessages({
  library(ShortRead)
  library(Matrix)
  library(tidyverse)
  library(sparseMatrixStats)
})

dir.tags <- snakemake@input[["dir"]]
tags <- readMM(paste0(dir.tags, "/counts_unfiltered/cells_x_features.mtx", ""))
cells <- read.table(paste0(dir.tags, "/counts_unfiltered/cells_x_features.barcodes.txt", ""), header = FALSE)
samples <- read.table(paste0(dir.tags, "/counts_unfiltered/cells_x_features.genes.txt", ""), header = FALSE)
rownames(tags) <- cells$V1
colnames(tags) <- samples$V1
tags <- as(tags, "CsparseMatrix")

## the 75% threshold is used to ensure a dominant sample tag
## and reduce the chance of misassignment
df1 <- data.frame(Cellular.Barcode = rownames(tags),
                  Sample.Tag = ifelse(sparseMatrixStats::rowMaxs(tags) >= 0.75 * rowSums(tags),
                                      colnames(tags)[max.col(tags)],
                                      "Multiplet"))
df1 <- df1[!df1$Sample.Tag == 'Multiplet', ]

write.table(df1, file = snakemake@output[["df1"]], 
            sep = "\t", row.names = FALSE, col.names = FALSE, quote = FALSE)