# config_demo.yaml

wta: false
multiplex: true

threads_number: "8"
sequencing_technology: "BDWTA"
genes_to_be_allele_typed: ["HLA-A","HLA-B","HLA-C","HLA-DPB1","HLA-DQB1","HLA-DQA1","HLA-DRB1"] # a list
raw_data_fastq_list: ["data/raw/PBMC.L001.R1.fastq.gz", "data/raw/PBMC.L001.R2.fastq.gz", "data/raw/PBMC.L002.R1.fastq.gz", "data/raw/PBMC.L002.R2.fastq.gz"] # a list; fastq files must have the following format: {dir_raw_fastq}/*.R{1/2}.fastq.gz

sample_tag_seqs: "data/meta/SampleTagSequences.fasta" # only if multiplexed

read_bp_length: "75" # only if amplicon-based
amplicon_cDNA_fasta: "data/meta/mRNAPanelRef.fasta" # only if amplicon-based

single_end_samples: true # only if whole-transcriptome-based
reference_genome_gtf: "data/meta/gtf.gz" # only if whole-transcriptome-based
reference_genome_fasta: "data/meta/dnaPrimaryAssembly.fa.gz" # only if whole-transcriptome-based
